from tkinter import *
def delete():
    pass

def click(event):
    global scavlue
    text=event.widget.cget("text")
    print(text)
    if(text=="="):
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            try:
             value=eval(screen.get())
            except Exception as e:
                value = "Erorr"


        scvalue.set(value)
        screen.update()

    elif(text=="C"):
        scvalue.set("")
        screen.update()

    else:
        scvalue.set(scvalue.get()+text)
        screen.update()

root = Tk()
root.geometry("400x600")
root.title("Anas Calcuator")
scvalue = StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font=" lucida 20 bold",bg="deep sky blue")
screen.pack(pady=20,ipadx=8,padx=10,fill=X)
f=Frame(root,bg="black")
b=Button(f,text="9",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind('<Button-1>', click)
b=Button(f,text="8",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="7",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="+",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="black")
b=Button(f,text="6",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind('<Button-1>', click)
b=Button(f,text="5",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="4",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="-",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="black")
b=Button(f,text="3",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind('<Button-1>', click)
b=Button(f,text="2",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="1",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="*",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="black")
b=Button(f,text="0",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind('<Button-1>', click)
b=Button(f,text="00",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="C",padx=28,pady=22,font="Arial 10 bold",bg="red")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="/",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
f=Frame(root,bg="black")
b=Button(f,text="0",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind('<Button-1>', click)
b=Button(f,text="00",padx=28,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="AC",padx=22,pady=22,font="Arial 10 bold",bg="yellow")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",delete)
b=Button(f,text="/",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="black")
b=Button(f,text="C",padx=28,pady=22,font="Arial 10 bold",bg="red")
b.pack(side=LEFT,padx=15,pady=10)
b.bind('<Button-1>', click)
b=Button(f,text="^",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="%",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
b=Button(f,text="=",padx=28,pady=22,font="Arial 10 bold",bg="white")
b.pack(side=LEFT,padx=15,pady=10)
b.bind("<Button-1>",click)
f.pack()

root.mainloop()